{% set name = "ussa1976" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ussa1976-{{ version }}.tar.gz
  sha256: 9ef7ea4c6991c8a3c176396ab6ce01a4211e8d6e91bbe97810986dc87c1920fa

build:
  entry_points:
    - ussa1976 = ussa1976.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - poetry
  host:
    - pip
    - python >=3.6,<3.10
    - poetry
  run:
    - click >=7.0
    - netcdf4 >=1.5.7
    - numpy >=1.22
    - python >=3.6,<3.10
    - scipy >=1.6.3
    - xarray >=0.18.2,<2022.4.0

test:
  imports:
    - ussa1976
  commands:
    - pip check
    - ussa1976 --help
  requires:
    - pip

about:
  home: https://github.com/nollety/ussa1976
  summary: The U.S. Standard Atmosphere 1976 model.
  description: |
    This package implements the atmosphere thermophysical model provided by the
    National Aeronautics and Space Administration technical report
    NASA-TM-X-74335 published in 1976 and entitled "U.S. Standard Atmosphere,
    1976".
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  doc_url: https://ussa1976.readthedocs.io/
  dev_url: https://github.com/nollety/ussa1976

extra:
  recipe-maintainers:
    - nollety
